### PR TITLE
Added local_build lane for build ipas locally

### PR DESCRIPTION
**Pull request by lucianomarisi**
I sometimes have the need to build an ipa locally for testing purposes, do you guys think it would be a good idea to add this lane onto the MasterFastfile?

### CODE REVIEW

**Review by Neil3079 — APPROVED** [review]

**Comment by zacoid55** [comment]
This will be great for creating ipas when we want to run automation on Xamarin's Testcloud

**Comment by lucianomarisi** [comment]
@Neil3079 @zacoid55  I include the icon_overlay action? Sometimes it's useful to know what was built but it may annoying if you don't have the dependencies installed.

**Comment by Neil3079** [comment]
@lucianomarisi could you make it a parameter of the lane so the user decides?

**Comment by lucianomarisi** [comment]
TIL: you can add parameter to lanes. I'll have a look and update the PR.

**Review by Neil3079 — APPROVED** [review]

**Review by Neil3079 — APPROVED** [review]

**Pull request merged**
